from datetime import datetime

# Construct the Markdown content
md = f"""# Weekly Intelligence Report

**Snapshot Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## 🎯 Strategic Focus Areas

* **Market Movements:** Tracking detached home velocity and PPSF shifts.
* **Infrastructure Updates:** Monitoring the Hazel McCallion LRT and Hospital expansion.
* **Policy Changes:** Analyzing 'Missing Middle' and DC Waiver opportunities.
* **Refinance Opportunities:** Assessing LTV thresholds for the Smith Maneuver.
* **Rental Income Strategies:** Optimizing basement suites and garden home yields.

---

### 📂 Quick Links
- [Market Radar](market.md)
- [Appraisal Intelligence](appraisal.md)
- [Infrastructure Catalysts](catalysts.md)
- [Mortgage Optimization](mortgage.md)
- [Housing Policy](policy.md)
- [property ](property.md)
---
*Generated by the 2026 Asset Intelligence System*
"""

# Save to the markdown file
with open("docs/weekly.md", "w") as f:
    f.write(md)

print("Weekly report successfully generated: docs/weekly.md")